import { inject, type Module } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { TypeCDocumentationProvider } from './documentation/tc-documentation-provider.js';
import { TypeCHoverProvider } from './documentation/tc-hover-provider.js';
import { TypeCGeneratedModule, TypeCGeneratedSharedModule } from './generated/module.js';
import { TypeCScopeComputation } from './scope-system/tc-scope-computation.js';
import { TypeCScopeProvider } from './scope-system/tc-scope-provider.js';
import { TypeCTypeProvider } from './typing/type-c-type-provider.js';
import { TypeCTypeSystemValidator } from './validations/type-system-validations.js';
import { FunctionOverloadValidator } from './validations/function-overload-validations.js';
import { TypeCVariableUsageValidator } from './validations/variable-usage-validation.js';
import { TypeCVariableInitializerValidator } from './validations/variable-initializer-validation.js';
import { DuplicateValidator } from './validations/duplicate-validations.js';
import { TypeCControlFlowValidator } from './validations/control-flow-validation.js';
import { TCWorkspaceManager } from './workspace/tc-workspace-manager.js';
import { registerValidationChecks } from './type-c-validator.js';
import { TypeCLinker } from './linking/tc-linker.js';
import { TypeCTypeUtils } from './typing/type-utils.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type TypeCAddedServices = {
    references: {
        ScopeComputation: TypeCScopeComputation,
        ScopeProvider: TypeCScopeProvider,
        Linker: TypeCLinker
    },
    typing: {
        TypeProvider: TypeCTypeProvider
        TypeUtils: TypeCTypeUtils
    },
    validation: {
        TypeSystemValidator: TypeCTypeSystemValidator,
        FunctionOverloadValidator: FunctionOverloadValidator,
        VariableUsageValidator: TypeCVariableUsageValidator,
        VariableInitializerValidator: TypeCVariableInitializerValidator,
        DuplicateValidator: DuplicateValidator,
        ControlFlowValidator: TypeCControlFlowValidator
    },
    documentation: {
        DocumentationProvider: TypeCDocumentationProvider
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type TypeCServices = LangiumServices & TypeCAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const TypeCModule: Module<TypeCServices, PartialLangiumServices & TypeCAddedServices> = {
    validation: {
        TypeSystemValidator: (services: TypeCServices) => new TypeCTypeSystemValidator(services),
        FunctionOverloadValidator: (services: TypeCServices) => new FunctionOverloadValidator(services),
        VariableUsageValidator: () => new TypeCVariableUsageValidator(),
        VariableInitializerValidator: () => new TypeCVariableInitializerValidator(),
        DuplicateValidator: (services: TypeCServices) => new DuplicateValidator(services),
        ControlFlowValidator: () => new TypeCControlFlowValidator()
    },
    references: {
        ScopeComputation: (services: LangiumServices) => new TypeCScopeComputation(services),
        ScopeProvider: (services: TypeCServices) => new TypeCScopeProvider(services),
        Linker: (services: TypeCServices) => new TypeCLinker(services),
    },
    typing: {
        TypeProvider: (services: TypeCServices) => new TypeCTypeProvider(services),
        TypeUtils: (services: TypeCServices) => new TypeCTypeUtils(services)
    },
    documentation: {
        DocumentationProvider: (services: TypeCServices) => new TypeCDocumentationProvider(services)
    },
    lsp: {
        HoverProvider: (services: TypeCServices) => new TypeCHoverProvider(services)
    }
};

export const TypeCSharedModule = {
    workspace: {
        WorkspaceManager: (services: LangiumSharedServices) => new TCWorkspaceManager(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createTypeCServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    TypeC: TypeCServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        TypeCGeneratedSharedModule,
        TypeCSharedModule
    );
    const TypeC = inject(
        createDefaultModule({ shared }),
        TypeCGeneratedModule,
        TypeCModule
    );
    shared.ServiceRegistry.register(TypeC);
    registerValidationChecks(TypeC);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, TypeC };
}
